# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hastaUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 739)
        MainWindow.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(120,200,100);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: rgb(170, 85, 0);\n"
"    color: rgb(255, 200, 127);\n"
"    \n"
"    selection-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid rgb(120,200,100);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: rgb(170, 85, 0);\n"
"    color: rgb(255, 200, 127);\n"
"}\n"
"QCheckBox {\n"
"    border: 2px solid rgb(120,200,100);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: rgb(170, 85, 0);\n"
"    color: rgb(255, 200, 127);\n"
"}\n"
"QComboBox {\n"
"    border: 2px solid rgb(120,200,100);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: rgb(170, 85, 0);\n"
"    color: rgb(255, 200, 127);\n"
"}\n"
"QSpinBox {\n"
"    border: 2px solid rgb(120,200,100);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: rgb(170, 85, 0);\n"
"    color: rgb(255, 200, 127);\n"
"}\n"
"\n"
"QListWidget {\n"
"    border: 2px solid rgb(120,200,100);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: rgb(170, 85, 0);\n"
"    color: rgb(255, 200, 127);\n"
"}\n"
"QRadioButton {\n"
"    border: 2px solid rgb(120,200,100);\n"
"    border-radius: 7px;\n"
"    padding-left: 7px;\n"
"    padding-right: 7px;\n"
"    background-color: rgb(170, 85, 0);\n"
"    color: rgb(255, 200, 127);\n"
"}\n"
"QLabel {\n"
"    border: 2px solid rgb(120,200,100);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: rgb(170, 85, 0);\n"
"    color: rgb(255, 200, 127);\n"
"}\n"
"\n"
"QMenu {\n"
"    border: 2px solid rgb(120,200,100);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: rgb(170, 85, 0);\n"
"    color: rgb(255, 200, 127);\n"
"}\n"
"\n"
"QMainWindow {\n"
"    border: 2px solid rgb(120,200,100);\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: rgb(170, 85, 0);\n"
"    color: rgb(255, 200, 127);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(730, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(880, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.calwDTarihi = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calwDTarihi.setGeometry(QtCore.QRect(380, 30, 312, 183))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calwDTarihi.setFont(font)
        self.calwDTarihi.setObjectName("calwDTarihi")
        self.lstServis = QtWidgets.QListWidget(self.centralwidget)
        self.lstServis.setGeometry(QtCore.QRect(870, 70, 111, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstServis.setFont(font)
        self.lstServis.setObjectName("lstServis")
        item = QtWidgets.QListWidgetItem()
        self.lstServis.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstServis.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstServis.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstServis.addItem(item)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(730, 70, 101, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.rdKadin = QtWidgets.QRadioButton(self.groupBox)
        self.rdKadin.setGeometry(QtCore.QRect(10, 10, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdKadin.setFont(font)
        self.rdKadin.setObjectName("rdKadin")
        self.rdErkek = QtWidgets.QRadioButton(self.groupBox)
        self.rdErkek.setGeometry(QtCore.QRect(10, 60, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdErkek.setFont(font)
        self.rdErkek.setObjectName("rdErkek")
        self.tblKayit = QtWidgets.QTableWidget(self.centralwidget)
        self.tblKayit.setGeometry(QtCore.QRect(10, 310, 1051, 321))
        self.tblKayit.setRowCount(50)
        self.tblKayit.setColumnCount(10)
        self.tblKayit.setObjectName("tblKayit")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 640, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lblKayitSayisi = QtWidgets.QLabel(self.centralwidget)
        self.lblKayitSayisi.setGeometry(QtCore.QRect(170, 640, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblKayitSayisi.setFont(font)
        self.lblKayitSayisi.setText("")
        self.lblKayitSayisi.setObjectName("lblKayitSayisi")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 270, 192))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lneTC = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneTC.setFont(font)
        self.lneTC.setObjectName("lneTC")
        self.horizontalLayout.addWidget(self.lneTC)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lneAdi = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneAdi.setFont(font)
        self.lneAdi.setObjectName("lneAdi")
        self.horizontalLayout_2.addWidget(self.lneAdi)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lneSoyadi = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneSoyadi.setFont(font)
        self.lneSoyadi.setObjectName("lneSoyadi")
        self.horizontalLayout_3.addWidget(self.lneSoyadi)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.chkMedeni = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chkMedeni.setFont(font)
        self.chkMedeni.setObjectName("chkMedeni")
        self.horizontalLayout_4.addWidget(self.chkMedeni)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.cmbKanGrubu = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbKanGrubu.setFont(font)
        self.cmbKanGrubu.setObjectName("cmbKanGrubu")
        self.cmbKanGrubu.addItem("")
        self.cmbKanGrubu.addItem("")
        self.cmbKanGrubu.addItem("")
        self.cmbKanGrubu.addItem("")
        self.cmbKanGrubu.addItem("")
        self.cmbKanGrubu.addItem("")
        self.cmbKanGrubu.addItem("")
        self.cmbKanGrubu.addItem("")
        self.horizontalLayout_5.addWidget(self.cmbKanGrubu)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.spnKilo = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spnKilo.setFont(font)
        self.spnKilo.setMinimum(40)
        self.spnKilo.setMaximum(200)
        self.spnKilo.setObjectName("spnKilo")
        self.horizontalLayout_6.addWidget(self.spnKilo)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(40, 250, 981, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnBul = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnBul.setFont(font)
        self.btnBul.setStyleSheet("")
        self.btnBul.setObjectName("btnBul")
        self.horizontalLayout_7.addWidget(self.btnBul)
        self.btnEkle = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEkle.setFont(font)
        self.btnEkle.setObjectName("btnEkle")
        self.horizontalLayout_7.addWidget(self.btnEkle)
        self.btnSil = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSil.setFont(font)
        self.btnSil.setObjectName("btnSil")
        self.horizontalLayout_7.addWidget(self.btnSil)
        self.btnListele = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnListele.setFont(font)
        self.btnListele.setObjectName("btnListele")
        self.horizontalLayout_7.addWidget(self.btnListele)
        self.btnGuncelle = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGuncelle.setFont(font)
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.horizontalLayout_7.addWidget(self.btnGuncelle)
        self.BtnCikis = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnCikis.setFont(font)
        self.BtnCikis.setObjectName("BtnCikis")
        self.horizontalLayout_7.addWidget(self.BtnCikis)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menubar.setObjectName("menubar")
        self.menuYard_m = QtWidgets.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuHakkinda = QtWidgets.QAction(MainWindow)
        self.menuHakkinda.setObjectName("menuHakkinda")
        self.menuYard_m.addAction(self.menuHakkinda)
        self.menubar.addAction(self.menuYard_m.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "D.Tarihi"))
        self.label_5.setText(_translate("MainWindow", "Cinsiyeti"))
        self.label_8.setText(_translate("MainWindow", "Servis"))
        __sortingEnabled = self.lstServis.isSortingEnabled()
        self.lstServis.setSortingEnabled(False)
        item = self.lstServis.item(0)
        item.setText(_translate("MainWindow", "Dahiliye"))
        item = self.lstServis.item(1)
        item.setText(_translate("MainWindow", "Ortopedi"))
        item = self.lstServis.item(2)
        item.setText(_translate("MainWindow", "Kardiyoloji"))
        item = self.lstServis.item(3)
        item.setText(_translate("MainWindow", "Noröloji"))
        self.lstServis.setSortingEnabled(__sortingEnabled)
        self.rdKadin.setText(_translate("MainWindow", "Kadın"))
        self.rdErkek.setText(_translate("MainWindow", "Erkek"))
        self.label_10.setText(_translate("MainWindow", "Kayıt Sayısı:"))
        self.label.setText(_translate("MainWindow", "TC No"))
        self.label_2.setText(_translate("MainWindow", "Adı"))
        self.label_3.setText(_translate("MainWindow", "Soyadı"))
        self.label_9.setText(_translate("MainWindow", "Medeni Hali"))
        self.chkMedeni.setText(_translate("MainWindow", "Evli"))
        self.label_6.setText(_translate("MainWindow", "Kan Grubu"))
        self.cmbKanGrubu.setItemText(0, _translate("MainWindow", "0 RH -"))
        self.cmbKanGrubu.setItemText(1, _translate("MainWindow", "0 RH +"))
        self.cmbKanGrubu.setItemText(2, _translate("MainWindow", "A RH -"))
        self.cmbKanGrubu.setItemText(3, _translate("MainWindow", "A RH +"))
        self.cmbKanGrubu.setItemText(4, _translate("MainWindow", "B RH -"))
        self.cmbKanGrubu.setItemText(5, _translate("MainWindow", "B RH +"))
        self.cmbKanGrubu.setItemText(6, _translate("MainWindow", "AB RH -"))
        self.cmbKanGrubu.setItemText(7, _translate("MainWindow", "AB RH +"))
        self.label_7.setText(_translate("MainWindow", "Kilosu"))
        self.spnKilo.setSuffix(_translate("MainWindow", " kg."))
        self.spnKilo.setPrefix(_translate("MainWindow", " "))
        self.btnBul.setText(_translate("MainWindow", "Bul"))
        self.btnEkle.setText(_translate("MainWindow", "Ekle"))
        self.btnSil.setText(_translate("MainWindow", "Sil"))
        self.btnListele.setText(_translate("MainWindow", "Listele"))
        self.btnGuncelle.setText(_translate("MainWindow", "Güncelle"))
        self.BtnCikis.setText(_translate("MainWindow", "Çıkış"))
        self.menuYard_m.setTitle(_translate("MainWindow", "Yardım"))
        self.menuHakkinda.setText(_translate("MainWindow", "Hakkında"))
