# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaSayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_anaSayfa(object):
    def setupUi(self, anaSayfa):
        anaSayfa.setObjectName("anaSayfa")
        anaSayfa.resize(578, 309)
        self.centralwidget = QtWidgets.QWidget(anaSayfa)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 80, 341, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        anaSayfa.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(anaSayfa)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 26))
        self.menubar.setObjectName("menubar")
        self.menuGiri = QtWidgets.QMenu(self.menubar)
        self.menuGiri.setObjectName("menuGiri")
        anaSayfa.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(anaSayfa)
        self.statusbar.setObjectName("statusbar")
        anaSayfa.setStatusBar(self.statusbar)
        self.menuGoster = QtWidgets.QAction(anaSayfa)
        self.menuGoster.setObjectName("menuGoster")
        self.menuGiri.addAction(self.menuGoster)
        self.menubar.addAction(self.menuGiri.menuAction())

        self.retranslateUi(anaSayfa)
        QtCore.QMetaObject.connectSlotsByName(anaSayfa)

    def retranslateUi(self, anaSayfa):
        _translate = QtCore.QCoreApplication.translate
        anaSayfa.setWindowTitle(_translate("anaSayfa", "Ana Sayfa"))
        self.label.setText(_translate("anaSayfa", "Burası yeni sayfa...."))
        self.menuGiri.setTitle(_translate("anaSayfa", "Giriş"))
        self.menuGoster.setText(_translate("anaSayfa", "Göster"))
