# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parolaUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(352, 247)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lneKullanici = QtWidgets.QLineEdit(self.centralwidget)
        self.lneKullanici.setGeometry(QtCore.QRect(140, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneKullanici.setFont(font)
        self.lneKullanici.setObjectName("lneKullanici")
        self.lneParola = QtWidgets.QLineEdit(self.centralwidget)
        self.lneParola.setGeometry(QtCore.QRect(140, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneParola.setFont(font)
        self.lneParola.setMaxLength(8)
        self.lneParola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneParola.setObjectName("lneParola")
        self.btnTamam = QtWidgets.QPushButton(self.centralwidget)
        self.btnTamam.setGeometry(QtCore.QRect(60, 120, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnTamam.setFont(font)
        self.btnTamam.setObjectName("btnTamam")
        self.btnIptal = QtWidgets.QPushButton(self.centralwidget)
        self.btnIptal.setGeometry(QtCore.QRect(190, 120, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnIptal.setFont(font)
        self.btnIptal.setObjectName("btnIptal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 352, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Kullanıcı Adı"))
        self.label_2.setText(_translate("MainWindow", "Parola"))
        self.btnTamam.setText(_translate("MainWindow", "Tamam"))
        self.btnIptal.setText(_translate("MainWindow", "İptal"))
